### ISSUE TITLE
Move on to API v2

### ISSUE THREAD

**Issue by etagwerker** [ombulabs/pecas#19]
Feedback from Freckle: Why don't we use API v2 or add support to it?

**Comment by mauro-oto** [comment]
@etagwerker I believe https://github.com/ryanlecompte/letsfreckle-client only supports v1. This project: https://github.com/timcraft/freckle seems to be newer, but supports v2. It seems that they have support for the API endpoints we need. We could consider moving over to that project instead, which also seems to be lightweight, relying only on native Ruby stuff.

**Comment by schmierkov** [comment]
@etagwerker @mauro-oto awesome, then let's use the newer client! :boom:
