### ISSUE TITLE
Prevent sending E-Mails on Holidays

### ISSUE THREAD

**Issue by schmierkov** [ombulabs/pecas#23]
We should not send notifications on holidays

**Comment by etagwerker** [comment]
@schmierkov what library/API could we use to find the national holidays per country? I found https://github.com/holidays/holidays but it doesn't seem to be up to date for Argentina: https://github.com/holidays/holidays/blob/30cb9f9da624f37df03a49676f8b4391cca5d355/definitions/ar.yaml 

Thoughts?

**Comment by schmierkov** [comment]
@etagwerker is was thinking about something more static too. I think the gem is fine, we just need to add a PR for updating the holidays. I will investigate the holidays here and prepare a PR for the holidays gem

**Comment by schmierkov** [comment]
@etagwerker I sent a PR to the holidays gem, which got merged already. I think we are good to use it for pecas. My idea was to add a env variable with the country code. What do you think?

**Comment by etagwerker** [comment]
@schmierkov I like that idea. Please go ahead and do it.

**Comment by schmierkov** [comment]
@etagwerker this issue will be fixed by #24
