### ISSUE TITLE
History tracking

### ISSUE THREAD

**Issue by mauro-oto** [ombulabs/pecas#3]
Hey @etagwerker, @schmierkov, 

It would be awesome to have the ability to browse the weekly history for all hours tracked per user/project, and not just for the current week.

**Comment by schmierkov** [comment]
@mauro-oto check out #16 which provides a switching of the weeks with simple links! tell me what you think :tada:

**Comment by mauro-oto** [comment]
Awesome :+1: closed through https://github.com/ombulabs/pecas/pull/16
