### ISSUE TITLE
Documentation - Start with rvmsudo

### ISSUE THREAD

**Issue by matiasmasca** [ombulabs/pecas#39]
Why you decide start rvm with sudo? Is a bad practice start an app with sudo 

The rvm documentation says:
Note: The Multi-User install instructions must be prefixed with the sudo command. However, once the install is complete, and the instructions to add users to the rvm group is followed, the use of either sudo or rvmsudo is no longer required. The sudo command is only to temporarily elevate privileges so the installer can complete its work. If you need to use sudo or rvmsudo after the install is complete, some part of the install directions were not properly followed. This usually is because people execute the install as root, rather than executing the installation instructions from a non-privileged user account.

**Comment by etagwerker** [comment]
@matiasmasca We usually do this in order to access the application through port 80. In this particular case it seems unnecessary.
