### ISSUE TITLE
Create demo data for a demo deployment

### ISSUE THREAD

**Issue by mauro-oto** [ombulabs/pecas#7]
Earlier today with @schmierkov we discussed the ability to create demo data for a demo deployment, so that we can show off our application with a proper demo application instead of our own internal app.

**Comment by etagwerker** [comment]
@mauro-oto Good idea. I think we should also work on this: https://github.com/ombulabs/freckler/issues/8

**Comment by schmierkov** [comment]
@etagwerker basic preparation for #8 is done by #10. we might need to adjust seeding to the demo application, but I would suggest doing this in another PR, what do you think @mauro-oto?
